version: "3.8"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - nginx-network
    env_file:
      - .env
  graphana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    networks:
      - nginx-network
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - nginx-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
networks:
  nginx-network:
    driver: bridge
