services:
  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - nginx-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - nginx-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  app:
    depends_on:
      - nginx
    restart: always
    image: kimfom01/trackyourspendings
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - nginx-network
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    networks:
      - nginx-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - nginx-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
networks:
  nginx-network:
    driver: bridge
