version: "3.8"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
    networks:
      - nginx-network
  app:
    restart: always
    image: kimfom01/trackyourspendings
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - nginx-network
    env_file:
      - .env
networks:
  nginx-network:
    driver: bridge
