version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: TrackYourSpending
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: TrackYourSpending/Web
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: TrackYourSpending/Test