# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: net-build
          path: ./

      # # - if: github.event_name == 'push'
      # - name: Decode SSL Certificate
      #   run: |
      #     mkdir ./Web/certs/ && touch ./Web/certs/cert.pfx
      #     cat "${{ secrets.SSL_CERT_BASE64 }}" | base64 -d > ./Web/certs/cert.pfx

      # # - if: github.event_name == 'push'
      # - name: Build Docker Image
      #   run: docker build -t kimfom01/trackyourspendings:latest .

      # # - if: github.event_name == 'push'
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # # - if: github.event_name == 'push'
      # - name: Push Image to Docker Hub
      #   run: docker push kimfom01/trackyourspendings:latest

  push-to-dockerhub:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: net-build
          path: output

      - name: Decode SSL Certificate
        run: |
          tree output
          cd output
          mkdir -p ./Web/certs/ && touch ./Web/certs/cert.pfx
          cat ${{ secrets.SSL_CERT_BASE64 }} | base64 -d > ./Web/certs/cert.pfx

      - name: Build Docker Image
        run: docker build -t kimfom01/trackyourspendings:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to Docker Hub
        run: docker push kimfom01/trackyourspendings:latest
